import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
import { Inter, Outfit } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import CustomCursor from "@/components/CustomCursor";
import Logo from "./components/Logo";


const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
});

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-outfit",
});

export const metadata = {
  title: "Brand And Port",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${outfit.variable} antialiased text-white`}
      >
        <CustomCursor />
        <Header />
        <Toaster />
        <Logo />
        {children}
        <Footer />
      </body>
    </html>
  );
}
